geo:
  locationCacheType: "files"
  locationCache: "/tmp/location_cache"
  nominatim:
    - name: "locationiq"
      type: "iq"
      url: "https://us1.locationiq.com/v1/search.php"
      token: "${LOCATIONIQ_TOKEN}"

ip:
  ipCacheType: "files"
  ipCache: "/tmp/ip_cache"
  geoip2: "/app/GeoLite2-City.mmdb"

weather:
  wwo:
    baseUrl: "https://api.worldweatheronline.com/premium/v1/weather.ashx?key={key}&q={q}&num_of_days=3&tp=3&format=json"
    key: "${WWO_KEY}"
    maxConns: 100

cache:
  size: 10000

logging:
  accessLog: "/tmp/access.log"
  errorsLog: "/tmp/errors.log"
  interval: 60

server:
  portHttp: 8002

renderer:
  subprocess: []
